# Service of type ClusterIP to expose nginx-on-each-node pods within the cluster
apiVersion: v1
kind: Service
metadata:
  name: nginx-on-each-node
  namespace: default
spec:
  selector:
    app: nginx-on-each-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP