apiVersion: v1
kind: Service
metadata:
  name: nginx-configmap-on-each-node
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nginx-configmap-on-each-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
