# ConfigMap containing the HTML file with the node name
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: default
data:
  index.html: |
    <html>
    <head><title>Node Info</title></head>
    <body>
      <h1>This pod is running on: $(NODE_NAME)</h1>
    </body>
    </html>
---
# DaemonSet to run nginx on each node, mounting the ConfigMap. But $(NODE_NAME) is seen as static data.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-on-each-node
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-on-each-node
  template:
    metadata:
      labels:
        app: nginx-on-each-node
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          hostPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-index
          