apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  persistence:
    storageClassName: ""
    storage: 8Gi
  
  override:
    statefulSet:
      spec:
        template:
          spec:
            initContainers:
            - name: fix-permissions
              image: busybox
              command:
              - sh
              - -c
              - |
                chown -R 999:999 /var/lib/rabbitmq
                chmod -R 755 /var/lib/rabbitmq
              volumeMounts:
              - name: persistence
                mountPath: /var/lib/rabbitmq
              securityContext:
                runAsUser: 0
            securityContext:
              fsGroup: 999
              runAsUser: 999
              runAsGroup: 999
            containers: []
