apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  persistence:
    storageClassName: ""
    storage: 8Gi
  
  override:
    statefulSet:
      spec:
        template:
          spec:
            securityContext:
              fsGroup: 999
              runAsUser: 999
              runAsGroup: 999
            containers: []
