apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-0
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/rabbitmq/data-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-1
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/rabbitmq/data-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-2
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/rabbitmq/data-2
